Repository kids-first/kf-lib-data-ingest, pull requests merged in 2019-05, with the labels that each got.

#279 🐛 Fix user defined test bugs
  kf_lib_data_ingest/etl/ingest_pipeline.py
  tests/conftest.py
  tests/test_app_settings.py
  tests/test_oauth2.py
  tests/test_pandas_utils.py
  tests/test_user_def_tests.py
Labels: bug

#254 ✨ Post transform accounting
  docs/source/tutorial/package_testing.rst
  kf_lib_data_ingest/app/cli.py
  kf_lib_data_ingest/common/concept_schema.py
  kf_lib_data_ingest/common/stage.py
  kf_lib_data_ingest/etl/extract/extract.py
  kf_lib_data_ingest/etl/ingest_pipeline.py
  kf_lib_data_ingest/etl/stage_analyses.py
  kf_lib_data_ingest/etl/transform/guided.py
  kf_lib_data_ingest/etl/transform/transform.py
  tests/test_create_new_ingest.py
  tests/test_ingest_pipeline.py
  tests/test_logging.py
Labels: feature

#290 🐛 Don't access attributes on strings
  kf_lib_data_ingest/etl/stage_analyses.py
  tests/test_stage_analyses.py
Labels: accounting, bug

#292 🚚 Mv network funcs into network utils
  kf_lib_data_ingest/common/misc.py
  kf_lib_data_ingest/etl/load/load.py
  kf_lib_data_ingest/etl/transform/transform.py
  kf_lib_data_ingest/network/oauth2.py
  kf_lib_data_ingest/network/utils.py
  tests/conftest.py
  tests/test_null_processing.py
Labels: refactor

#297 💬 Don't start concept strings with 'CONCEPT|'
  docs/source/tutorial/package_testing.rst
  docs/source/tutorial/transform.rst
  kf_lib_data_ingest/common/concept_schema.py
  kf_lib_data_ingest/common/pandas_utils.py
  tests/data/test_study/extract_outputs/simple_tsv_example1_output.tsv
  tests/data/test_study/extract_outputs/simple_tsv_example2_output.tsv
  tests/data/test_study/extract_outputs/split_rows_tsv_example1_output.tsv
  tests/data/test_study/extract_outputs/unsimple_xlsx_example1_output.tsv
  tests/test_concept_schema.py
  tests/test_ingest_pipeline.py
Labels: refactor

#293 🔊 Log release version and commit sha
  Dockerfile
  kf_lib_data_ingest/__init__.py
  kf_lib_data_ingest/config.py
  kf_lib_data_ingest/etl/ingest_pipeline.py
  setup.py
  tests/test_ingest_pipeline.py
Labels: feature

#303 🐛 Fix numeric_to_str - vals that equate to 0 should return '0'
  kf_lib_data_ingest/common/misc.py
  tests/test_misc.py
Labels: bug

#305 ✨ Write transform stage output to TSV
  kf_lib_data_ingest/etl/transform/guided.py
  kf_lib_data_ingest/etl/transform/transform.py
  tests/test_transform_stage.py
Labels: feature

#309 🐛 Load entities in order defined by target api cfg
  kf_lib_data_ingest/etl/load/load.py
  templates/my_study/ingest_package_config.py
  tests/data/SD_ME0WME0W/ingest_package_config.py
  tests/test_load_stage.py
Labels: bug

#314 🐛🔧 Fix/update genomic file std and target concept configuration
  kf_lib_data_ingest/common/concept_schema.py
  kf_lib_data_ingest/common/constants.py
  kf_lib_data_ingest/target_apis/kids_first.py
  tests/data/test_boyd_study/extract_configs/s3_files_kf-seq-data-hudsonalpha_haib17SB5136_map.py
  tests/data/test_study/extract_configs/simple_tsv_example2.py
  tests/data/test_study/extract_configs/unsimple_xlsx_example1.py
  tests/data/test_study/extract_outputs/simple_tsv_example2_output.tsv
  tests/data/test_study/extract_outputs/unsimple_xlsx_example1_output.tsv
Labels: bug
