Repository kids-first/kf-lib-data-ingest, pull requests merged in 2019-06, with the labels that each got.

#316 🐛 Load objects instead of object-like strings
  kf_lib_data_ingest/common/misc.py
  kf_lib_data_ingest/etl/load/load.py
  kf_lib_data_ingest/etl/transform/transform.py
  tests/test_extract_stage.py
  tests/test_misc.py
Labels: bug

#299 ✨ Run subsets of ingest pipeline
  docs/source/tutorial/debugging.rst
  docs/source/tutorial/index.rst
  kf_lib_data_ingest/app/cli.py
  kf_lib_data_ingest/common/misc.py
  kf_lib_data_ingest/common/stage.py
  kf_lib_data_ingest/etl/ingest_pipeline.py
  kf_lib_data_ingest/etl/load/load.py
  tests/data/simple_study/data/clinical.tsv
  tests/data/simple_study/extract_configs/extract_config.py
  tests/data/simple_study/ingest_package_config.py
  tests/data/simple_study/transform_module.py
  tests/test_ingest_pipeline.py
  tests/test_load_stage.py
Labels: feature

#322 ♻️ Transform function outputs dict of DataFrames
  docs/source/tutorial/transform.rst
  kf_lib_data_ingest/config.py
  kf_lib_data_ingest/etl/transform/guided.py
  kf_lib_data_ingest/etl/transform/transform.py
  templates/my_study/transform_module.py
  tests/data/SD_ME0WME0W/transform_module.py
  tests/data/simple_study/transform_module.py
  tests/data/test_boyd_study/transform_module.py
  tests/data/test_study/transform_module.py
  tests/data/test_study/transform_module_simple.py
  tests/test_guided_transform.py
  tests/test_null_processing.py
  tests/test_transform_stage.py
Labels: refactor

#319 ♻️ Refactor links in target api cfg
  kf_lib_data_ingest/etl/configuration/target_api_config.py
  kf_lib_data_ingest/etl/load/load.py
  kf_lib_data_ingest/etl/transform/guided.py
  kf_lib_data_ingest/etl/transform/standard_model/model.py
  kf_lib_data_ingest/etl/transform/transform.py
  kf_lib_data_ingest/target_apis/kids_first.py
  tests/test_guided_transform.py
  tests/test_standard_model.py
  tests/test_target_api_config.py
Labels: refactor

#324 ✨ Add family relationship to concept schema and kids first api config
  kf_lib_data_ingest/common/concept_schema.py
  kf_lib_data_ingest/target_apis/kids_first.py
Labels: feature

#315 ✨ Add grouping of Splits
  kf_lib_data_ingest/common/misc.py
  kf_lib_data_ingest/common/pandas_utils.py
  kf_lib_data_ingest/etl/extract/extract.py
  requirements.txt
  tests/test_logging.py
  tests/test_pandas_utils.py
Labels: feature

#329 🐛 Fix invalid use of pytest context managers
  tests/data/simple_study/extract_configs/extract_config.py
  tests/test_app_settings.py
  tests/test_concept_graph.py
  tests/test_configs.py
  tests/test_extract_operations.py
  tests/test_extract_stage.py
  tests/test_file_retriever.py
  tests/test_guided_transform.py
  tests/test_ingest_stage.py
  tests/test_logging.py
  tests/test_standard_model.py
  tests/test_target_api_config.py
  tests/test_transform_stage.py
  tests/test_type_safety.py
Labels: bug

#333 🐛 Fix merge col validation bug in merge_wo_duplicates
  kf_lib_data_ingest/common/pandas_utils.py
  tests/test_pandas_utils.py
Labels: bug

#327 ✨ Support resuming load from a given target ID or prefix
  kf_lib_data_ingest/app/cli.py
  kf_lib_data_ingest/etl/ingest_pipeline.py
  kf_lib_data_ingest/etl/load/load.py
Labels: feature

#330 ♻️ Refactor BIOSPECIMEN concept -> BIOSPECIMEN, BIOSPECIMEN_GROUP
  kf_lib_data_ingest/common/concept_schema.py
  kf_lib_data_ingest/etl/transform/guided.py
  kf_lib_data_ingest/target_apis/kids_first.py
  templates/my_study/extract_configs/extract_config.py
  tests/data/SD_ME0WME0W/extract_configs/clinical.py
  tests/data/simple_study/extract_configs/extract_config.py
  tests/data/test_boyd_study/extract_configs/Boyd_Minimal_Data_Elements_Cuellar_9-2-2018_EDITED_v2_map.py
  tests/data/test_boyd_study/extract_configs/manifest_180917_rectified_map.py
  tests/data/test_boyd_study/transform_module.py
  tests/data/test_study/extract_configs/simple_tsv_example2.py
  tests/data/test_study/extract_configs/split_rows_tsv_example1.py
  tests/data/test_study/extract_configs/unsimple_xlsx_example1.py
  tests/data/test_study/extract_outputs/simple_tsv_example2_output.tsv
  tests/data/test_study/extract_outputs/split_rows_tsv_example1_output.tsv
  tests/data/test_study/extract_outputs/unsimple_xlsx_example1_output.tsv
  tests/data/test_study/ingest_package_config.py
  tests/test_guided_transform.py
  tests/test_ingest_pipeline.py
  tests/test_standard_model.py
  tests/test_transform_stage.py
Labels: bug, refactor

#348 👷 Blanket ignore all dotfiles
  .gitignore
Labels: refactor

#347 ✨ Add ETag to constants
  kf_lib_data_ingest/common/constants.py
Labels: feature

#349 👷 Updates Constants
  kf_lib_data_ingest/common/constants.py
Labels: feature
