Repository kids-first/kf-lib-data-ingest, pull requests merged in 2019-03, with the labels that each got.

#164 ✨ Small Logging Improvements
  kf_lib_data_ingest/cli.py
  kf_lib_data_ingest/config.py
  kf_lib_data_ingest/etl/configuration/dataset_ingest_config.py
  kf_lib_data_ingest/etl/configuration/log.py
  kf_lib_data_ingest/etl/ingest_pipeline.py
  tests/test_logging.py
Labels: feature, refactor

#165 👷Run ingest in CI to verify build worked
  scripts/build.sh
  scripts/test.sh
Labels: devops

#152 ✨ Kids First Null Processing
  .gitignore
  kf_lib_data_ingest/common/misc.py
  kf_lib_data_ingest/config.py
  kf_lib_data_ingest/etl/ingest_pipeline.py
  kf_lib_data_ingest/etl/transform/transform.py
  kf_lib_data_ingest/target_apis/kids_first.py
  tests/conftest.py
  tests/data/mock_dataservice_schema.json
  tests/test_null_processing.py
  tests/test_transform_stage.py
Labels: feature

#172 ✨ Make ingest-pipeline.png clickable
  docs/source/index.rst
Labels: documentation

#174 🐛 🔊 Fix null processing and better logging
  kf_lib_data_ingest/etl/transform/common.py
  kf_lib_data_ingest/etl/transform/transform.py
  tests/test_null_processing.py
Labels: bug

#181 🖼 Update logo
  README.md
  docs/source/_static/images/logo.svg
Labels: documentation

#184 ♻️ Preserve original file's ext in fetched temp file
  kf_lib_data_ingest/common/file_retriever.py
  kf_lib_data_ingest/etl/extract/extract.py
  tests/test_extract_stage.py
  tests/test_file_retriever.py
Labels: refactor

#195 ♻️ Refactor guided transform stage
  kf_lib_data_ingest/common/pandas_utils.py
  kf_lib_data_ingest/etl/transform/auto.py
  kf_lib_data_ingest/etl/transform/guided.py
  kf_lib_data_ingest/etl/transform/transform.py
  kf_lib_data_ingest/factory/templates/my_study/transform_module.py
  tests/conftest.py
  tests/data/test_study/transform_module.py
  tests/data/test_study/transform_module_simple.py
  tests/test_guided_transform.py
  tests/test_null_processing.py
  tests/test_pandas_utils.py
  tests/test_transform_stage.py
Labels: refactor

#206 🐛 Rm ingest test_study from build.sh
  scripts/build.sh
Labels: bug

#208 🐛 Use safe YAML loader
  kf_lib_data_ingest/common/misc.py
Labels: bug
