Repository kids-first/kf-lib-data-ingest, pull requests merged in 2019-04, with the labels that each got.

#199 ✨ Add auth to file retriever
  kf_lib_data_ingest/common/file_retriever.py
  kf_lib_data_ingest/common/misc.py
  kf_lib_data_ingest/etl/configuration/log.py
  kf_lib_data_ingest/network/oauth2.py
  kf_lib_data_ingest/network/utils.py
  tests/conftest.py
  tests/mocks.py
  tests/test_file_retriever.py
  tests/test_oauth2.py
Labels: feature

#221 🐛 Fix rogue nulls
  kf_lib_data_ingest/etl/transform/guided.py
  kf_lib_data_ingest/etl/transform/transform.py
  tests/test_guided_transform.py
  tests/test_transform_stage.py
Labels: bug

#224 ♻️ Make target api file fields, class var names consistent
  kf_lib_data_ingest/etl/configuration/target_api_config.py
  kf_lib_data_ingest/etl/transform/guided.py
  kf_lib_data_ingest/etl/transform/standard_model/model.py
  kf_lib_data_ingest/etl/transform/transform.py
  tests/test_guided_transform.py
  tests/test_null_processing.py
  tests/test_standard_model.py
Labels: refactor

#210 ✨ App settings
  kf_lib_data_ingest/app/cli.py
  kf_lib_data_ingest/app/settings/__init__.py
  kf_lib_data_ingest/app/settings/base.py
  kf_lib_data_ingest/app/settings/development.py
  kf_lib_data_ingest/app/settings/production.py
  kf_lib_data_ingest/config.py
  kf_lib_data_ingest/etl/extract/extract.py
  kf_lib_data_ingest/etl/ingest_pipeline.py
  setup.py
  tests/conftest.py
  tests/data/test_study/extract_config_development.py
  tests/data/test_study/extract_config_production.py
  tests/test_app_settings.py
  tests/test_create_new_ingest.py
  tests/test_ingest_pipeline.py
  tests/test_logging.py
  tests/test_null_processing.py
Labels: feature

#230 ♻️ Make template ingest pkg usable
  kf_lib_data_ingest/factory/templates/my_study/data/clinical.tsv
  kf_lib_data_ingest/factory/templates/my_study/dataset_ingest_config.yml
  kf_lib_data_ingest/factory/templates/my_study/extract_configs/extract_config.py
  kf_lib_data_ingest/factory/templates/my_study/transform_module.py
  tests/test_create_new_ingest.py
Labels: refactor

#214 🐳 Dockerize ingest app
  .dockerignore
  Dockerfile
  scripts/entrypoint.sh
  tests/data/SD_ME0WME0W/dataset_ingest_config.yml
  tests/data/SD_ME0WME0W/extract_configs/simple_tsv_example1.py
  tests/data/SD_ME0WME0W/extract_configs/simple_tsv_example2.py
  tests/data/SD_ME0WME0W/extract_configs/split_rows_tsv_example1.py
  tests/data/SD_ME0WME0W/extract_configs/unsimple_xlsx_example1.py
  tests/data/SD_ME0WME0W/transform_module.py
Labels: devops

#235 📝 Clean up README
  README.md
Labels: documentation

#237 ♻️ Use term "ingest package" consistently in docs site
  docs/source/index.rst
  docs/source/tutorial/index.rst
  docs/source/tutorial/ingest_package.rst
  docs/source/tutorial/project_setup.rst
Labels: documentation

#238 🐛 Fix bug with optional components in unique keys
  kf_lib_data_ingest/common/concept_schema.py
  kf_lib_data_ingest/etl/transform/transform.py
  tests/test_transform_stage.py
Labels: bug

#231 ✅ User defined data validation tests
  kf_lib_data_ingest/app/cli.py
  kf_lib_data_ingest/config.py
  kf_lib_data_ingest/etl/ingest_pipeline.py
  kf_lib_data_ingest/factory/generate.py
  kf_lib_data_ingest/factory/templates/my_study/data/clinical.tsv
  templates/my_study/data/clinical.tsv
  templates/my_study/dataset_ingest_config.yml
  templates/my_study/extract_configs/extract_config.py
  templates/my_study/tests/conftest.py
  templates/my_study/tests/test_custom_counts.py
  templates/my_study/transform_module.py
  tests/pytest.ini
  tests/test_create_new_ingest.py
  tests/test_standard_model.py
Labels: feature

#189 ✨ Add Test CLI cmd
  kf_lib_data_ingest/app/cli.py
  tests/test_ingest_pipeline.py
Labels: feature

#225 👷 Add Jenkinsfile
  Jenkinsfile
Labels: devops

#242 🐛 Add missing pytest and re-org dev-requirements
  dev-requirements.txt
  requirements.txt
Labels: refactor

#239 📝 Update tutorial - test ingest package, transform stg
  docs/data/family_and_phenotype.tsv
  docs/source/index.rst
  docs/source/tutorial/extract.rst
  docs/source/tutorial/index.rst
  docs/source/tutorial/package_testing.rst
  docs/source/tutorial/project_setup.rst
  docs/source/tutorial/transform.rst
Labels: documentation

#244 🐛 Update broken link in extract tutorial
  docs/source/tutorial/extract.rst
Labels: bug

#252 🐳 Docker container clean up after ingest ends
  scripts/entrypoint.sh
Labels: devops

#253 🔒 lock down merges
  CODEOWNERS
Labels: devops

#257 🔥 Rm docker self clean from entrypoint
  scripts/entrypoint.sh
Labels: devops

#266 🐛 Fix logging with fetching files
  kf_lib_data_ingest/common/file_retriever.py
  kf_lib_data_ingest/network/utils.py
Labels: bug, refactor

#262 ✨ Add app settings sect to docs
  docs/source/index.rst
  docs/source/tutorial/app.rst
  docs/source/tutorial/extract.rst
  docs/source/tutorial/index.rst
Labels: documentation

#267 🔧 Update dev settings - pass token in req header
  docs/source/tutorial/extract.rst
  kf_lib_data_ingest/app/settings/development.py
  tests/test_file_retriever.py
Labels: refactor
