Repository kids-first/kf-lib-data-ingest, pull requests merged in 2019-02, with the labels that each got.

#110 💄 Update docs to use Kids First Style
  README.md
  doc-requirements.txt
  docs/source/_static/css/style.css
  docs/source/_static/images/logo.png
  docs/source/_templates/layout.html
  docs/source/conf.py
  docs/source/index.rst
  docs/source/reference/common.rst
Labels: documentation

#119 👷 Fix CI Scripts
  dev-requirements.txt
  doc-requirements.txt
  scripts/build.sh
  scripts/test.sh
  tests/test_file_retriever.py
Labels: bug, devops

#109 📝 how to configure a new study
  doc-requirements.txt
  docs/source/conf.py
  docs/source/developer.rst
  docs/source/index.rst
  docs/source/install.rst
  docs/source/quickstart.rst
  docs/source/tutorial/extract.rst
  docs/source/tutorial/index.rst
  docs/source/tutorial/project_setup.rst
  docs/source/tutorial/study_configuration.rst
  scripts/build.sh
Labels: documentation

#142 ✨ Unique Key Refactor and Other Fixes
  kf_lib_data_ingest/cli.py
  kf_lib_data_ingest/common/concept_schema.py
  kf_lib_data_ingest/etl/transform/common.py
  kf_lib_data_ingest/etl/transform/transform.py
  tests/test_ingest_pipeline.py
  tests/test_standard_model.py
  tests/test_transform_stage.py
Labels: refactor

#149 ✨ Finish guided transform
  kf_lib_data_ingest/etl/transform/guided.py
  kf_lib_data_ingest/etl/transform/transform.py
  tests/data/test_boyd_study/dataset_ingest_config.yml
  tests/data/test_boyd_study/extract_configs/manifest_180917_rectified_map.py
  tests/data/test_boyd_study/extract_configs/s3_files_kf-seq-data-hudsonalpha_haib17SB5136_map.py
  tests/data/test_boyd_study/transform_module.py
  tests/test_guided_transform.py
  tests/test_transform_stage.py
Labels: feature
