Repository kids-first/kf-lib-data-ingest, pull requests merged in 2020-09, with the labels that each got.

#484 ✨ Add sequencing centers
  kf_lib_data_ingest/common/constants.py
Labels: feature

#486 ✨ Define validation test input structure
  kf_lib_data_ingest/common/constants.py
  kf_lib_data_ingest/validation/values.py
Labels: feature

#492 🔥 Remove old accounting code
  kf_lib_data_ingest/common/stage.py
  kf_lib_data_ingest/etl/ingest_pipeline.py
  kf_lib_data_ingest/etl/stage_analyses.py
  kf_lib_data_ingest/templates/my_study/tests/conftest.py
  kf_lib_data_ingest/templates/my_study/tests/test_custom_counts.py
  tests/test_create_new_ingest.py
  tests/test_ingest_pipeline.py
  tests/test_logging.py
  tests/test_stage_analyses.py
Labels: refactor

#496 ✨🚧Create skeleton code for CLI validate command
  kf_lib_data_ingest/app/cli.py
  kf_lib_data_ingest/common/io.py
  kf_lib_data_ingest/validation/validation.py
  tests/test_validation.py
Labels: feature

#507 🐛 Fix path_to_file_list
  kf_lib_data_ingest/common/io.py
Labels: bug
