Repository kids-first/kf-lib-data-ingest, pull requests merged in 2021-02, with the labels that each got.

#570 🔊 🐛 More verbose loader logging + loader fixes
  kf_lib_data_ingest/etl/load/load_v1.py
  kf_lib_data_ingest/etl/load/load_v2.py
  kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py
Labels: feature

#572 🏷 Release 1.0.0
  CHANGELOG.md
Labels: release

#574 💚 Remove requirement for job in testing workflow
  .github/workflows/publish.yml
Labels: bug, devops
